package com.compofelice.stiereats.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.compofelice.stiereats.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await

/**
 * Google Sign-In → Firebase Auth, the Android identity path.
 *
 * The resulting Firebase UID is stable across reinstalls (unlike anonymous
 * auth), which is exactly why Android uses federated sign-in where iOS can
 * lean on iCloud. That UID is the user's key in Firestore (FirestoreRepository).
 *
 * Uses the modern Credential Manager + Google ID token flow. The server
 * ("web") client id is `R.string.default_web_client_id`, auto-generated by the
 * google-services Gradle plugin from google-services.json — so it only resolves
 * once the real config file is dropped into app/.
 */
class AuthManager(
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
) {
    val isSignedIn: Boolean get() = auth.currentUser != null
    val uid: String? get() = auth.currentUser?.uid
    val displayName: String? get() = auth.currentUser?.displayName

    /**
     * Prompt for a Google account and sign in to Firebase. Throws on
     * cancellation / failure so the caller can surface a message.
     */
    suspend fun signInWithGoogle(context: Context) {
        val serverClientId = context.getString(R.string.default_web_client_id)
        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(true)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val result = CredentialManager.create(context).getCredential(context, request)
        val credential = result.credential
        val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken

        val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(firebaseCredential).await()
    }

    fun signOut() = auth.signOut()
}
